Ktlint and Detekt linters implemented
Coding-Pit-Dev/PVPC-Android pull request #3
Opened 2024-08-07 14:06 UTC by martamdf

## Descripción de los cambios
---
Se agregan los plugins de Ktlint y Detekt al proyecto. Se crea una Baseline en Detekt para obviar (de primeras) los incumplimientos de base del proyecto. 

### Finalidad de la PR
---
 
- [ ] 🐛 (Bug)
- [X] 🧑🏻‍💻 (Feature)
- [ ] 🌶️ (Hotfix)

### Tipo de cambio
---
 
- [ ] Corrección de errores 
- [X] Nueva característica
- [ ] Mejora 
- [ ] Refactorización 
- [ ] Documentación 
- [ ] Otros

### Checklist
---

 

- [X] He seguido las directrices del código.
- [X] He realizado una revisión de código local.
- [X] He ejecutado las pruebas y todas pasan.
- [ ] He añadido pruebas que prueban mis cambios.
- [X] He actualizado la documentación si es necesario.

### Cómo probar los cambios
---
Ejecutar desde la terminal de AS:  `./gradlew ktlintCheck`  y  `./gradlew detekt ` (comandos para macOS).

### URL de la tarea
---
Añadir Linters al proyecto:
https://app.clickup.com/t/86bzgzu4t

2024-08-07 14:45 UTC, juanjecilla requested changes

2024-08-08 20:56 UTC, martamdf commented on app/build.gradle.kts
> +    disabledRules.set(listOf("no-wildcard-imports", "final-newline"))
Corregido! Se quedan las reglas que tiene Ktlint por defecto.

2024-08-08 20:57 UTC, martamdf commented on gradle/libs.versions.toml
> +ktlint = "11.0.0"
He aprovechado para incluir también este cambio.

2024-08-09 07:38 UTC, juanjecilla approved these changes
All good, gracias!

2024-08-09 13:43 UTC, merged