ADD task Añadir bottom bar
Coding-Pit-Dev/PVPC-Android pull request #50
Opened 2024-12-12 18:45 UTC by DanielSerranoDev

ADD task Añadir bottom bar

2024-12-12 18:52 UTC, juanjecilla commented
@DanielSerranoDev los nombres de las ramas no tienen que contener caracteres raros. La ñ a partir de ahora prohibida.

2024-12-12 18:58 UTC, juanjecilla requested changes

2024-12-12 18:58 UTC, juanjecilla commented on app/src/main/java/com/codingpit/pvpcplanner/ui/main/MainComponents/MainBottomBarNav.kt
> +            selected = selectedScreen == "HomeScreen",
Saca esto a una clase que tenga los parámetros necesarios, así no hay que cambiarlo en cada momento. También puedes hacer un forEach de todos lo elementos que haya y así si luego añadimos más elementos, no hay que ponerlo a mano.

2024-12-12 18:58 UTC, juanjecilla commented on app/src/main/java/com/codingpit/pvpcplanner/ui/main/MainComponents/MainBottomBarNav.kt
> +                text = "Home",
Todos los strings tienen que ir al fichero strings.xml

2024-12-12 18:58 UTC, juanjecilla commented on app/src/main/java/com/codingpit/pvpcplanner/ui/main/MainComponents/MainContent.kt
> +fun MainContent(
Para que necesitas este composable?

2024-12-12 18:58 UTC, juanjecilla commented on app/src/main/java/com/codingpit/pvpcplanner/ui/main/MainScreen.kt
> +    var selectedScreen by remember { mutableStateOf("MapScreen") }
Lo mismo, create un objeto o algo que agrupe todo y no sea un string a pelo.

2024-12-17 20:05 UTC, DanielSerranoDev commented on app/src/main/java/com/codingpit/pvpcplanner/ui/main/MainComponents/MainBottomBarNav.kt
> +            selected = selectedScreen == "HomeScreen",
creado un object constant val con los elementos y un foreach.

2024-12-17 20:06 UTC, DanielSerranoDev commented on app/src/main/java/com/codingpit/pvpcplanner/ui/main/MainComponents/MainBottomBarNav.kt
> +                text = "Home",
He creado una constante, tengo tambien hacer un fichero strings.xml aun asi?

2024-12-17 20:07 UTC, DanielSerranoDev commented on app/src/main/java/com/codingpit/pvpcplanner/ui/main/MainComponents/MainContent.kt
> +fun MainContent(
Para ahora despues elegir la pantalla, se puede reducir todo en el screen, pero lo he separado. Que hacemos?

2024-12-17 20:07 UTC, DanielSerranoDev commented on app/src/main/java/com/codingpit/pvpcplanner/ui/main/MainScreen.kt
> +    var selectedScreen by remember { mutableStateOf("MapScreen") }
Creado contants

2024-12-21 16:20 UTC, juanjecilla submitted a review, later dismissed

2024-12-21 16:20 UTC, juanjecilla commented on app/src/main/java/com/codingpit/pvpcplanner/data/Constants.kt
> +
Aquí hay unos espacios extra.

2024-12-23 08:45 UTC, DanielSerranoDev commented on app/src/main/java/com/codingpit/pvpcplanner/data/Constants.kt
> +
Ok, arreglado y movido constants a folder utils

2024-12-23 08:56 UTC, juanjecilla approved these changes, later dismissed

2024-12-23 09:00 UTC, DanielSerranoDev commented
![image](https://github.com/user-attachments/assets/c2bb633c-5fc5-4dfc-b4de-480c07845227)

2024-12-23 09:03 UTC, juanjecilla commented
eso es porque has llamado a la rama "añadir-", no se deben meter ñs

2024-12-23 09:04 UTC, juanjecilla approved these changes

2024-12-23 17:52 UTC, merged