Feature/GitHub actions
Coding-Pit-Dev/PVPC-Android pull request #7
Opened 2024-08-27 16:21 UTC by martamdf

## Descripción de los cambios
---
Se agrega archivo ci.yml, en el que se incluye un workflow para que cada vez que se realice un push/pull request a develop o a main, se haga un build de la aplicación. 

### Finalidad de la PR
---
 
- [ ] 🐛 (Bug)
- [X] 🧑🏻‍💻 (Feature)
- [ ] 🌶️ (Hotfix)

### Tipo de cambio
---
 
- [ ] Corrección de errores 
- [X] Nueva característica
- [ ] Mejora 
- [ ] Refactorización 
- [ ] Documentación 
- [ ] Otros

### Checklist
---

 

- [X] He seguido las directrices del código.
- [X] He realizado una revisión de código local.
- [X] He ejecutado las pruebas y todas pasan.
- [ ] He añadido pruebas que prueban mis cambios.
- [X] He actualizado la documentación si es necesario.

### Cómo probar los cambios
---
En la pestaña Actions, se ejecutará el trabajo cada vez que se haga un Push o una Pull Request a la rama Main o Develop.

### URL de la tarea
---
Configurar Github Actions:
https://app.clickup.com/t/86bzhg1ph

2024-09-01 08:41 UTC, juanjecilla requested changes
@martamdf hay que añadir también un paso en el pipeline para que se ejecuten los tests.

2024-09-02 19:54 UTC, juanjecilla requested changes
Perdón por los cambios.

2024-09-02 19:54 UTC, juanjecilla commented on .github/workflows/ci.yml
> +        branches: [ 'main', 'develop', 'github_actions' ]
Ahora que veo esto. Queremos que se haga para cada push, sea en la rama que sea de momento. Y como se hace para cada push, no nos hace falta hacerlo para las PRs.

2024-09-02 19:59 UTC, juanjecilla commented on .github/workflows/ci.yml
> +        branches: [ 'main', 'develop', 'github_actions' ]
Así se va a ejecutar sólo en main y develop. También para las PRs.

2024-09-02 20:02 UTC, juanjecilla commented on .github/workflows/ci.yml
> +        branches: [ 'main', 'develop', 'github_actions' ]
Déjalo sólo en 

push:
       - '*'    
       
  quita lo de pull_request

2024-09-02 20:04 UTC, juanjecilla approved these changes

2024-09-02 20:05 UTC, martamdf commented on .github/workflows/ci.yml
> +        branches: [ 'main', 'develop', 'github_actions' ]
Lo he dejado así: 
on:
    push:

En principio así entiendo que ejecuta el workflow en todos los push, y nada en las PRs.

2024-09-02 20:06 UTC, merged