Feature/retrofit
Coding-Pit-Dev/PVPC-Android pull request #8
Opened 2024-09-07 18:06 UTC by DanielSerranoDev

Añadido retrofit, dagger, test. Tambien remotedatasource

2024-09-07 18:06 UTC, DanielSerranoDev commented
pullrequest rama retrofit

2024-09-07 18:08 UTC, DanielSerranoDev commented
branch retrofit + develop

2024-09-09 10:43 UTC, juanjecilla requested changes
Revisa los comentarios

2024-09-09 10:43 UTC, juanjecilla commented on app/build.gradle.kts
> +    kotlin("kapt")
esto añadelo con el mismo sistema que los otros

2024-09-09 10:43 UTC, juanjecilla commented on app/build.gradle.kts
> +    implementation(libs.gson)
No nos gusta Gson, usa Moshi o kotlin-serialization.

2024-09-09 10:43 UTC, juanjecilla commented on app/src/main/java/com/codingpit/pvpcplanner/di/NetworkModule.kt
> +    private const val BASE_URL = "https://api.com/"
Esto no es correcto.

2024-09-09 10:43 UTC, juanjecilla commented on app/src/main/java/com/codingpit/pvpcplanner/di/NetworkModule.kt
> +                val originalRequest = chain.request()
No estás haciendo nada con el interceptor, por lo tanto no nos sirve de nada.

2024-09-09 10:43 UTC, juanjecilla commented on app/src/main/java/com/codingpit/pvpcplanner/domains/models/PVPCModel.kt
> +    var id: Int?,
Por qué es var y nulable?

2024-09-09 10:43 UTC, juanjecilla commented on app/src/test/java/com/codingpit/pvpcplanner/data/remote/RemoteDataSourceTest.kt
> +        val mockResponse = listOf(
Puedes sacar estas variables a una clase aparte para poder reutilizarlas en otros sitios.

2024-09-09 10:43 UTC, juanjecilla commented on app/src/test/java/com/codingpit/pvpcplanner/data/remote/RemoteDataSourceTest.kt
> +    fun `getPrices handles API exception`() = runBlocking {
Cambia el nombre para que siga la nomenclatura de when/given/then

2024-09-09 10:43 UTC, juanjecilla commented on gradle.properties
> +org.gradle.warning.mode=all
Para qué has añadido esto?

2024-09-09 10:43 UTC, juanjecilla commented on gradle/libs.versions.toml
> +activityCompose = "1.9.1"
Las dependencias no podemos cambiarlas así tan alegremente y si se hace, tiene que ser en una PR aparte ya que no tiene que ver con retrofit

2024-09-09 18:05 UTC, DanielSerranoDev commented on gradle/libs.versions.toml
> +activityCompose = "1.9.1"
ok

2024-09-09 18:06 UTC, DanielSerranoDev commented on gradle.properties
> +org.gradle.warning.mode=all
Unas pruebas con la con el error de la version del graddle, lo que hace es que te arroje todos los datos. Ya he encontrado el error, era el plugin de kapt esta obsoleto para esta version me dice.

2024-09-09 18:09 UTC, DanielSerranoDev commented on app/build.gradle.kts
> +    kotlin("kapt")
Me arroja error el kapt, porque esta obsoleto, ha sido quitarlo y me ha funcionado. Hay que ver mas sobre esto, o hacer otra cosa

2024-09-09 18:09 UTC, DanielSerranoDev commented on app/build.gradle.kts
> +    implementation(libs.gson)
ok, eliminado

2024-09-09 18:10 UTC, DanielSerranoDev commented on app/src/main/java/com/codingpit/pvpcplanner/di/NetworkModule.kt
> +    private const val BASE_URL = "https://api.com/"
He puesto la misma base url que en el proyecto de IOS https://api.esios.ree.es/archives/70/download_json

2024-09-09 18:12 UTC, DanielSerranoDev commented on app/src/main/java/com/codingpit/pvpcplanner/di/NetworkModule.kt
> +                val originalRequest = chain.request()
Ok, eliminado

2024-09-09 18:13 UTC, DanielSerranoDev commented on app/src/main/java/com/codingpit/pvpcplanner/domains/models/PVPCModel.kt
> +    var id: Int?,
Modificado a constante y quitado nulable, porque siempre tiene que haber uno.

2024-09-09 18:25 UTC, DanielSerranoDev commented on app/src/test/java/com/codingpit/pvpcplanner/data/remote/RemoteDataSourceTest.kt
> +        val mockResponse = listOf(
Tengo duda, lo saque a una clase que se llama mocks.

 private lateinit var mocks: Mocks ¿tengo que instanciarla con un late init?

2024-09-09 18:44 UTC, DanielSerranoDev commented on app/src/test/java/com/codingpit/pvpcplanner/data/remote/RemoteDataSourceTest.kt
> +    fun `getPrices handles API exception`() = runBlocking {
OK

2024-09-10 09:37 UTC, juanjecilla commented on app/build.gradle.kts
> +     kapt(libs.hilt.compiler)
Hay un espacio extra aquí

2024-09-10 09:37 UTC, juanjecilla commented on app/src/main/java/com/codingpit/pvpcplanner/domains/models/PVPCModel.kt
> +
Hay una linea extra aquí.

2024-09-10 09:37 UTC, juanjecilla commented on app/src/main/java/com/codingpit/pvpcplanner/domains/models/PVPCModel.kt
> +
Hay una linea extra aquí.

2024-09-10 09:38 UTC, juanjecilla requested changes
Unos cambios pequeños, aunque queda los nombres de los tests

2024-09-11 19:15 UTC, DanielSerranoDev commented
Ok, modificado nombre tests

2024-09-12 08:52 UTC, DanielSerranoDev commented
Que le queda a esto @juanjecilla ?

2024-09-12 10:14 UTC, juanjecilla approved these changes, later dismissed
Todo en orden ya

2024-09-12 10:14 UTC, juanjecilla commented
@DanielSerranoDev aprueba y mergea

2024-09-12 11:06 UTC, DanielSerranoDev reviewed
Revisado

2024-09-12 11:26 UTC, juanjecilla approved these changes

2024-09-12 11:26 UTC, merged